services:
  - type: web
    name: watch-together-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server-deploy.js
    envVars:
      - key: NODE_ENV
        value: production
